- build.gradle
- src/main/java/com/api/ttoklip/domain/base/BaseEntity.java
- src/main/java/com/api/ttoklip/domain/base/BaseEntityConfig.java
- src/main/java/com/api/ttoklip/domain/base/BaseTimeEntity.java
- src/main/java/com/api/ttoklip/global/config/QuerydslConfig.java
- src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
- src/main/java/com/api/ttoklip/global/config/SwaggerConfig.java
- src/main/java/com/api/ttoklip/global/exception/ApiException.java
- src/main/java/com/api/ttoklip/global/exception/ApiExceptionHandler.java
- src/main/java/com/api/ttoklip/global/exception/ApiExceptionResponse.java
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
- src/main/java/com/api/ttoklip/global/s3/S3ClientConfig.java
- src/main/java/com/api/ttoklip/global/s3/S3FileUploader.java
- src/main/java/com/api/ttoklip/global/success/SuccessResponse.java
- src/main/java/com/api/ttoklip/global/success/SuccessResponseStatus.java
- src/main/java/com/api/ttoklip/global/success/SuccessStatus.java
- src/main/java/com/api/ttoklip/global/util/SecurityUtil.java
이슈 번호 : #1 
ex) 기본 config와 util, exception, SuccessResponse, BaseEntity를 추가하였습니다.
ex) 후에 ~api 연결 필요
~~~
- feat : 새로운 기능 구현
- add : feat 이외의 부수적인 코드, 파일, 라이브러리 추가
- chore : 패키지 구조, 함수 및 변수명 변경 등의 작은 작업
- fix : 버그 및 오류 해결
- del : 불필요한 코드, 파일, 주석 삭제
- docs : 명세서 작성
- refactor : 코드 리팩토링
- merge : 서로 다른 브랜치 간의 코드 병합
- setting : 프로젝트 기초 세팅 관련 작업
~~~
~~~
Feature/{type}-{작업 내용}
ex)
Feature/feat-home-api
feature/add-review-crud
~~~
> Setting/1 초기세팅

- src/main/java/com/api/ttoklip/domain/privacy/constant/PrivacyConstant.java
- src/main/java/com/api/ttoklip/domain/privacy/controller/ProfileController.java
- src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
- src/main/java/com/api/ttoklip/global/security/auth/controller/AuthController.java
- src/main/java/com/api/ttoklip/global/security/auth/dto/LoginRequest.java
- src/main/java/com/api/ttoklip/global/security/auth/service/OAuth2UserInfoFactory.java
- src/main/java/com/api/ttoklip/global/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
- src/main/resources/application.yml
이슈 번호
#54 
머지 후 9번 매핑 브랜치에서 작업했어야 했는데 이미 머지한 54번 브랜치에서 작업한 내용을 pr합니다.
> pr fix web 로그인 방식 sdk 로그인 방식 활용

- build.gradle
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
- src/main/java/com/api/ttoklip/global/security/auth/service/OAuth2UserInfoFactory.java
- src/main/java/com/api/ttoklip/global/security/auth/userInfo/KakaoUserInfo.java
- src/main/java/com/api/ttoklip/global/security/auth/userInfo/NaverUserInfo.java
이슈 번호
- #58 
oauth 요청 후 error custom
> pr Fix/4 invalid oauth accesstoken error custom

- src/main/java/com/api/ttoklip/domain/honeytip/post/domain/HoneyTip.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/domain/Newsletter.java
- src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
이슈 번호
- #60 
ex) 홈 화면 api를 구현하였습니다.
> fix: 회원가입하고 개인정보 입력 안했을 때 isFirstLogin true처리

- src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityCommonService.java
이슈 번호
- #42
1. Member와 게시글 댓글 연관관계 매핑
2. 함께해요 글 작성자가 참여 인원 정해지면 마감하기
3. 소통해요 좋아요, 스크랩
4. 소통해요 게시글 조회 시 좋아요 수, 댓글 수
5. 글 목록에선 좋아요 수, 스크랩 수, 댓글 수
1. 함께해요 위치 로직
> pr Feat/9 우리동네 좋아요, 스크랩 빌드 오류 수정

- src/main/java/com/api/ttoklip/domain/honeytip/post/domain/HoneyTip.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/service/HoneyTipPostService.java
- src/main/java/com/api/ttoklip/domain/honeytip/scrap/domain/HoneyTipScrap.java
- src/main/java/com/api/ttoklip/domain/honeytip/scrap/repository/HoneyTipScrapRepository.java
- src/main/java/com/api/ttoklip/domain/honeytip/scrap/repository/HoneyTipScrapRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/honeytip/scrap/service/HoneyTipScrapService.java
- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/dto/response/NewsletterSingleResponse.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
이슈 번호
- #67 
- 단건 조회 
- 단건 조회 시 댓글 수 포함
- 멤버 엔티티에 OneToMany 추가
- Scrap 디렉토리 => scrap으로 수정
> pr Fix/6 뉴스레터 단건조회수정

- src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipDefaultRepository.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipRepositoryImpl.java
이슈 번호
- #70 
Scrap 디렉토리명 변경으로 인해 발생한 query dsl import error 해결
> pr Fix/7 query dsl import error

- src/main/java/com/api/ttoklip/domain/honeytip/like/service/HoneyTipLikeService.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/dto/response/HoneyTipSingleResponse.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/service/HoneyTipPostService.java
- src/main/java/com/api/ttoklip/domain/honeytip/scrap/service/HoneyTipScrapService.java
- src/main/java/com/api/ttoklip/domain/newsletter/like/service/NewsletterLikeService.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/dto/response/NewsletterSingleResponse.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
- src/main/java/com/api/ttoklip/domain/newsletter/scarp/service/NewsletterScrapService.java
- src/main/java/com/api/ttoklip/domain/town/community/like/service/CommunityLikeService.java
- src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunitySingleResponse.java
- src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
- src/main/java/com/api/ttoklip/domain/town/community/scrap/service/CommunityScrapService.java
이슈 번호
- #72 
꿀팁공유해요, 뉴스레터, 소통해요 - 좋아요, 스크랩 여부를 응답에 추가로 반환하였습니다.
댓글 좋아요 여부도 위와 같이 해주시면 감사하겠습니다!
> pr Feat/14 like scrap value

- src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipSearchRepository.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterSearchRepository.java
- src/main/java/com/api/ttoklip/domain/search/controller/SearchController.java
- src/main/java/com/api/ttoklip/domain/search/response/CommunitySingleResponse.java
- src/main/java/com/api/ttoklip/domain/search/response/SingleResponse.java
- src/main/java/com/api/ttoklip/domain/search/service/SearchService.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
이슈 번호
- #78 
ex) 홈 화면 api를 구현하였습니다.
Mypage에서 본인이 작성한 글, 본인이 스크랩한 글 갖고올 때 SingleResponse, CommmunitySIngleResponse 사용하시던데 그곳을 조립할 때 사용하는 쿼리에서 comments, scrap, like 조인하셔야 dto조합할 때 InitiallizedException이 발생하지 않습니다!!
@psae0714 확인 부탁드립니다.
> pr Feat/10 search api apply response field

- src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipDefaultRepository.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipSearchRepository.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
이슈 번호
- #81 
검색, 기본 메인화면 조회시 비활성화(soft delete) 꿀팁공유해요, 소통해요를 보이지 않게 수정했습니다.
> pr Fix/10 main categories honeytip deactivity post fiilter

- src/main/java/com/api/ttoklip/domain/main/constant/QuestionResponseConstant.java
- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/question/comment/controller/QuestionCommentController.java
- src/main/java/com/api/ttoklip/domain/question/comment/domain/QuestionComment.java
- src/main/java/com/api/ttoklip/domain/question/comment/service/QuestionCommentService.java
- src/main/java/com/api/ttoklip/domain/question/like/entity/CommentLike.java
- src/main/java/com/api/ttoklip/domain/question/like/repository/CommentLikeRepository.java
- src/main/java/com/api/ttoklip/domain/question/like/repository/CommentLikeRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/question/like/service/CommentLikeService.java
- src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
- src/main/java/com/api/ttoklip/domain/question/post/domain/Question.java
- src/main/java/com/api/ttoklip/domain/question/post/dto/response/QuestionSingleResponse.java
- src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/question/post/service/QuestionCommonService.java
- src/main/java/com/api/ttoklip/domain/question/post/service/QuestionPostService.java
이슈 번호
- #74 
질문해요 댓글 좋아요 기능과 현재 사용자의 좋아요 여부 확인을 추가하였습니다.
> pr Feat/15 question comment like, likedByCurrentUser value

- aws/task_definition.json
> setting: 태스크 정의 한국으로 고정

- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/town/cart/constant/CartResponseConstant.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/dto/request/CartCreateRequest.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/entity/Cart.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/entity/CartMember.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartMemberRepository.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartMemberRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartMemberService.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
- src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
- src/main/java/com/api/ttoklip/global/success/Message.java
이슈 번호 : #85 
- 함께해요 공구 참여
- 함께해요 공구 취소
- 공구 인원 수 체크
ex) 후에 ~api 연결 필요
~~~
- feat : 새로운 기능 구현
- add : feat 이외의 부수적인 코드, 파일, 라이브러리 추가
- chore : 패키지 구조, 함수 및 변수명 변경 등의 작은 작업
- fix : 버그 및 오류 해결
- del : 불필요한 코드, 파일, 주석 삭제
- docs : 명세서 작성
- refactor : 코드 리팩토링
- merge : 서로 다른 브랜치 간의 코드 병합
- setting : 프로젝트 기초 세팅 관련 작업
~~~
> pr Refactor/2 cart party, party delete, party count

- src/main/java/com/api/ttoklip/domain/member/repository/MemberOAuthRepository.java
- src/main/java/com/api/ttoklip/domain/member/service/MemberService.java
- src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
- src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyCommunityRepostiory.java
- src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyHoneyTipRepository.java
- src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyQuestionRepository.java
- src/main/java/com/api/ttoklip/domain/mypage/noti/post/domain/NoticePagingRepository.java
- src/main/java/com/api/ttoklip/domain/mypage/term/dto/request/TermCreateRequest.java
- src/main/java/com/api/ttoklip/domain/stranger/constant/StrangerConstant.java
- src/main/java/com/api/ttoklip/domain/stranger/controller/StrangerController.java
- src/main/java/com/api/ttoklip/domain/stranger/dto/response/StrangerResponse.java
- src/main/java/com/api/ttoklip/domain/stranger/repository/StrangerHoneyTipRepository.java
- src/main/java/com/api/ttoklip/domain/stranger/service/StrangerService.java
#86 
타 유저의 프로필 불러오기와 꿀팁 공유헤요 기능구현 했습니다
비활성화된 객체는 가져오지 않도록 페이징 레포들 쿼리 수정했습니다. 거래내역 기능은 함께해요 기능구현이후 구현하겠습니다 street구현 필요합니다!
> pr feat 타인의 프로필 불러오기 꿀팁 공유해요 목록 페이징

- src/main/java/com/api/ttoklip/domain/home/service/HomeService.java
- src/main/java/com/api/ttoklip/domain/town/community/post/entity/Community.java
이슈 번호
- #92 
weatherService 제거, @Builder.Default 적용
> fix: weatherService 제거, @Builder.Default 적용

- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/question/comment/domain/QuestionComment.java
- src/main/java/com/api/ttoklip/domain/question/comment/dto/response/QuestionCommentResponse.java
- src/main/java/com/api/ttoklip/domain/question/comment/service/QuestionCommentService.java
- src/main/java/com/api/ttoklip/domain/question/like/entity/CommentLike.java
- src/main/java/com/api/ttoklip/domain/question/like/service/CommentLikeService.java
- src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
- src/main/java/com/api/ttoklip/domain/question/post/dto/response/QuestionSingleResponse.java
- src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/question/post/service/QuestionPostService.java
- src/main/java/com/api/ttoklip/domain/search/response/CommunitySingleResponse.java
- src/main/java/com/api/ttoklip/domain/search/response/SingleResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
- src/main/java/com/api/ttoklip/domain/town/main/constant/TownResponseConstant.java
- src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
- src/main/java/com/api/ttoklip/domain/town/main/dto/request/TownSearchCondition.java
- src/main/java/com/api/ttoklip/domain/town/main/dto/response/TownMainResponse.java
- src/main/java/com/api/ttoklip/domain/town/main/repository/CommunityPageRepository.java
- src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
이슈 번호 : #95 
- 소통해요 글목록 페이징 
- 질문해요 댓글 좋아요 유무 수정
ex) 후에 ~api 연결 필요
~~~
- feat : 새로운 기능 구현
- add : feat 이외의 부수적인 코드, 파일, 라이브러리 추가
- chore : 패키지 구조, 함수 및 변수명 변경 등의 작은 작업
- fix : 버그 및 오류 해결
- del : 불필요한 코드, 파일, 주석 삭제
- docs : 명세서 작성
- refactor : 코드 리팩토링
- merge : 서로 다른 브랜치 간의 코드 병합
- setting : 프로젝트 기초 세팅 관련 작업
~~~
> pr Feat/20 community paging

- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/privacy/service/ProfileService.java
> pr fix: 회원정보 생성 및 수정 누락 커밋 추가

- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/member/editor/MemberEditor.java
- src/main/java/com/api/ttoklip/domain/privacy/dto/PrivacyCreateRequest.java
- src/main/java/com/api/ttoklip/domain/privacy/service/ProfileService.java
> fix: HomeController 명세서 작성

- src/main/java/com/api/ttoklip/domain/honeytip/post/dto/request/HoneyTipCreateReq.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/dto/request/HoneyTipEditReq.java
- src/main/java/com/api/ttoklip/domain/mypage/noti/post/dto/request/NoticeCreateRequest.java
- src/main/java/com/api/ttoklip/domain/mypage/noti/post/dto/request/NoticeEditRequest.java
- src/main/java/com/api/ttoklip/domain/mypage/term/dto/request/TermCreateRequest.java
- src/main/java/com/api/ttoklip/domain/mypage/term/dto/request/TermEditRequest.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/dto/request/NewsletterCreateReq.java
- src/main/java/com/api/ttoklip/domain/question/post/dto/request/QuestionCreateRequest.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/dto/request/CartCreateRequest.java
- src/main/java/com/api/ttoklip/domain/town/community/post/dto/request/CommunityCreateRequest.java
이슈 번호
- #117 
게시글 생성시 제목, 내용 글 제한 범위 수정
> fix: 제한 범위 변경

- src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CartMainResponse.java
- src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunityRecent3Response.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
- src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
- src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
이슈 번호
- #119 
우리동네 메인 - 3개씩 추출
> feat: 우리동네 메인 - 3개씩 추출

- src/main/java/com/api/ttoklip/domain/common/comment/service/CommentService.java
- src/main/java/com/api/ttoklip/domain/member/service/MemberService.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/controller/NewsletterController.java
- src/main/java/com/api/ttoklip/domain/notification/service/FCMService.java
- src/main/java/com/api/ttoklip/global/config/AsyncConfig.java
- src/main/java/com/api/ttoklip/global/config/FCMConfig.java
이슈 번호 :
- #131
알림 기능 관련 에러 수정하였습니다.
Bean -> PostConstruct 방식으로 초기화하여 FirebaseMessaging 객체 초기화 오류를 해결했습니다.
왠지는 모르겠으나 프론트 쪽에서 FCM 갯수 카운팅 안되는 현상..
> Fix/7 알림 기능 테스트 및 에러 수정

- src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
- src/main/java/com/api/ttoklip/domain/email/dto/request/EmailSendRequest.java
- src/main/java/com/api/ttoklip/domain/email/dto/request/EmailVerifyRequest.java
- src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
- #157 
메일 전송, 검증 명세서 수정하였습니다.
> pr Docs/8 separating email requests

- src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
- src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
- src/main/java/com/api/ttoklip/domain/privacy/dto/InterestResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/constant/CartResponseConstant.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartGroupMemberResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartMemberResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
- src/main/java/com/api/ttoklip/global/security/auth/dto/request/AuthRequest.java
- src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
- #162 
함께해요(Cart)에 참여했다면 참여자(CartGroupMember)를 확인할 수 있도록 하는 기능을 구현하였습니다.
응답은 다음과 같습니다.
> pr Feat/31 check cart members

- src/main/resources/templates/mail.html
- #166 
다양한 이메일 클라이언트에서 파일 형식이 깨지지 않도록 인증코드 메일 폼을 수정하였습니다.
> pr Fix/18 modify email form

- src/main/java/com/api/ttoklip/domain/term/controller/TermController.java
- src/main/java/com/api/ttoklip/domain/term/dto/response/TermAdminResponse.java
- src/main/java/com/api/ttoklip/domain/term/repository/TermAgreementRepository.java
- src/main/java/com/api/ttoklip/domain/term/service/TermService.java
- src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
- src/main/java/com/api/ttoklip/global/security/auth/controller/AuthController.java
- src/main/java/com/api/ttoklip/global/security/auth/dto/response/TermClientResponse.java
- src/main/java/com/api/ttoklip/global/security/auth/dto/response/TermSignUpResponse.java
- src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
- src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
이슈 번호
- #172
1. 회원가입 전용 이용약관 조회 ap를 생성하였습니다.
2. 이용약관 관리를 관리자 전용 API로 분리하였습니다.
> pr Fix/20 회원가입 전용 이용약관 조회 api

- src/main/java/com/api/ttoklip/domain/common/comment/dto/response/CommentResponse.java
- src/main/java/com/api/ttoklip/domain/honeytip/post/dto/response/HoneyTipSingleResponse.java
- src/main/java/com/api/ttoklip/domain/main/dto/response/TitleResponse.java
- src/main/java/com/api/ttoklip/domain/mypage/domain/MyCartRepository.java
- src/main/java/com/api/ttoklip/domain/mypage/domain/MyCommunityRepostiory.java
- src/main/java/com/api/ttoklip/domain/mypage/domain/MyHoneyTipRepository.java
- src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserCartSingleResponse.java
- src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserSingleResponse.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/dto/response/NewsletterSingleResponse.java
- src/main/java/com/api/ttoklip/domain/question/comment/dto/response/QuestionCommentResponse.java
- src/main/java/com/api/ttoklip/domain/question/comment/repository/QuestionCommentRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/question/comment/service/QuestionCommentService.java
- src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
- src/main/java/com/api/ttoklip/domain/question/post/dto/response/QuestionSingleResponse.java
- src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionDefaultRepository.java
- src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/search/response/CommunitySingleResponse.java
- src/main/java/com/api/ttoklip/domain/search/response/SingleResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartSearchRepository.java
- src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunitySingleResponse.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
이슈 번호 : #178 
게시글들과 댓글에서 작성자의 프로필 이미지를 확인할 수 있도록 구현하였습니다
ex) 후에 ~api 연결 필요
~~~
- feat : 새로운 기능 구현
- add : feat 이외의 부수적인 코드, 파일, 라이브러리 추가
- chore : 패키지 구조, 함수 및 변수명 변경 등의 작은 작업
- fix : 버그 및 오류 해결
- del : 불필요한 코드, 파일, 주석 삭제
- docs : 명세서 작성
- refactor : 코드 리팩토링
- merge : 서로 다른 브랜치 간의 코드 병합
- setting : 프로젝트 기초 세팅 관련 작업
~~~
~~~
Feature/{이슈 번호 x, feat 순서}-{작업 내용}
ex)
Feature/3-home-api
Feature/4-home-crud
~~~
> pr Fix/21 profile post ripple

- src/main/resources/application.yml
이슈 번호
- #184 
ECS 띄워놓은 AWS 계정의 DB로 주소 변경
> setting: Change DB Source

- src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
- src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
> fix: createCode change only number

- src/main/java/com/api/ttoklip/domain/newsletter/post/controller/NewsletterController.java
- src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
이슈 번호 : 
-  #187 
뉴스레터 생성 권한을 변경하였습니다.
> feat: newsletter create admin

- src/main/java/com/api/ttoklip/domain/mypage/domain/MyCommunityPagingRepository.java
- src/main/java/com/api/ttoklip/domain/mypage/domain/MyCommunityRepostiory.java
- src/main/java/com/api/ttoklip/domain/mypage/service/MyPageService.java
> fix: community 잘못된 페이징 쿼리 수정

- build.gradle
- #195
배포 시 중복 파일로 인해 발생하는 문제 해결
> pr Fix/24 exclude duplicate setting

- src/main/resources/application.yml
> seeting: change aws-credentials (#203)

- src/main/resources/application.yml
> setting: logging.level warn으로 변경

- src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
> fix: 잘못된 newsletter getActivatedNewsletterFromComments() query 수정

- src/main/java/com/api/ttoklip/domain/town/TownCriteria.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
- src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
- src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
이슈 번호
- #214 
CITY("시"), DISTRICT("구"), TOWN("동")으로 구분
> feat: 소통해요 페이징 조회시 같은 지역으로 필터링. 시, 구, 동으로 구분 (#214)

- src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipSearchRepository.java
- src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
이슈 번호
- #223
제목 검색 -> 제목 + 내용 검색
> fix: 제목만 검색 -> 제목 + 내용 (#224)

- src/main/java/com/api/ttoklip/domain/aop/filtering/TownAspect.java
- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
이슈 번호
- #226 
서비스 서울 한정에서 전국으로 확대
> fix: 서비스 서울 한정에서 전국으로 확대

- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
- src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
> fix: 소통해요 필터링 기능 반영

- src/main/java/com/api/ttoklip/domain/member/dto/response/MemberStreetResponse.java
> fix: 주소 반환 공백 양쪽 제거

- src/main/java/com/api/ttoklip/domain/member/controller/MemberController.java
- src/main/java/com/api/ttoklip/domain/member/domain/Member.java
- src/main/java/com/api/ttoklip/domain/member/domain/Role.java
- src/main/java/com/api/ttoklip/domain/member/domain/vo/Provider.java
- src/main/java/com/api/ttoklip/domain/member/domain/vo/Role.java
- src/main/java/com/api/ttoklip/domain/member/facade/MemberFacade.java
- src/main/java/com/api/ttoklip/domain/member/repository/MemberJpaRepository.java
- src/main/java/com/api/ttoklip/domain/member/repository/MemberQueryRepository.java
- src/main/java/com/api/ttoklip/domain/member/repository/MemberRepository.java
- src/main/java/com/api/ttoklip/domain/member/repository/MemberRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/member/service/MemberService.java
- src/main/java/com/api/ttoklip/domain/mypage/controller/MyPageController.java
- src/main/java/com/api/ttoklip/domain/mypage/service/MyPageService.java
- src/main/java/com/api/ttoklip/domain/newsletter/facade/NewsletterPostFacade.java
- src/main/java/com/api/ttoklip/domain/profile/ProfileController.java
- src/main/java/com/api/ttoklip/domain/profile/ProfileLike.java
- src/main/java/com/api/ttoklip/domain/profile/ProfileLikeRepository.java
- src/main/java/com/api/ttoklip/domain/profile/ProfileLikeRepositoryCustom.java
- src/main/java/com/api/ttoklip/domain/profile/ProfileLikeRepositoryImpl.java
- src/main/java/com/api/ttoklip/domain/profile/ProfileLikeService.java
- src/main/java/com/api/ttoklip/domain/profile/TargetMemberProfile.java
- src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
- src/main/java/com/api/ttoklip/global/exception/ErrorType.java
- src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
- src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
- src/main/java/com/api/ttoklip/global/security/oauth2/dto/OAuthLoginRequest.java
- src/main/java/com/api/ttoklip/global/security/oauth2/service/OAuthRegisterService.java
- src/main/java/com/api/ttoklip/global/security/oauth2/service/OAuthService.java
- src/testFixtures/java/member/fixture/MemberFixture.java
이슈 번호
- #251 
#233  방식 그대로 Member도 Facade를 사용하도록 수정합니다.
> refactor: duplicated service to facade - 멤버

- .github/workflows/deploy.yml
- .gitignore
- src/main/java/com/api/ttoklip/domain/privacy/dto/PrivacyCreateRequest.java
- src/main/java/com/api/ttoklip/global/security/auth/dto/request/AuthRequest.java
> fix: 주소 trim

- .github/workflows/deploy.yml
- .gitignore
- src/main/java/com/api/ttoklip/domain/privacy/dto/PrivacyCreateRequest.java
- src/main/java/com/api/ttoklip/global/security/auth/dto/request/AuthRequest.java
- src/main/java/com/api/ttoklip/global/util/BadWordFilter.java
> fix: 욕설 검증시 공백 제거 동작 취소

- docker-compose.dev.yml
- docker-compose.prod.yml
- nginx/nginx.conf
- ttoklip-infrastructure/src/main/resources/application-infra-prod.yml
이슈 번호
- #272 
1. 단일 Dockerfile을 docker-compose를 통해 여러 애플리케이션을 사용하도록 변경하였습니다.
2. 서버 앞단에 NGINX 부착하였습니다.
> Setting: 단일 dockerfile docker compose 로 변경 nginx 부착

- .gitignore
- docker-compose.dev.yml
- nginx/nginx.conf
- settings.gradle
- ttoklip-api/build.gradle
- ttoklip-api/src/main/java/com/api/global/config/SecurityConfig.java
- ttoklip-api/src/main/java/com/api/global/jwt/JwtAuthenticationFilter.java
- ttoklip-api/src/main/resources/application-api-dev.yml
- ttoklip-api/src/main/resources/application-api-prod.yml
- ttoklip-batch/build.gradle
- ttoklip-batch/src/main/resources/application-batch-dev.yml
- ttoklip-batch/src/main/resources/application-batch-prod.yml
- ttoklip-infrastructure/build.gradle
- ttoklip-monitoring/build.gradle
- ttoklip-monitoring/docker-compose.monitoring.yml
- ttoklip-monitoring/loki/config/loki-local-config.yaml
- ttoklip-monitoring/prometheus/prometheus.yml
- ttoklip-monitoring/promtail/config/promtail-local-config.yaml
- ttoklip-monitoring/src/main/resources/application.yml
이슈 번호
- #274 
매트릭 수집, 시각화, 로그 수집
> feat: 모니터링 부착
